---

- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: vim
      state: present

  - name: Install nginx
    yum:
      name: curl
      state: present

  - name: Insert Index Page
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html

  - name: run this command and ignore the result
    shell: /usr/bin/env
